version: '3.8'

services:
 flask_app:
   build: .
   env_file:
      - .env
   environment:
     SQLALCHEMY_DATABASE_URI: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
   ports: 
    - "8080:8080"
   depends_on:
      - db
   
     
 db:
   image: postgres:latest
   env_file:
      - .env
   volumes:
     - .:/dockoer-entrypoint-initdb.d
